export const CREATE = 'users/CREATE'
export const AUTHENTICATE_FACEBOOK = 'users/AUTHENTICATE_FACEBOOK'

export const CREATE_ERROR = 'users/CREATE_ERROR'
export const CREATE_SUCCESS = 'users/CREATE_SUCCESS'

export const AUTHENTICATE_FACEBOOK_ERROR = 'users/AUTHENTICATE_FACEBOOK_ERROR'
export const AUTHENTICATE_FACEBOOK_SUCCESS = 'users/AUTHENTICATE_FACEBOOK_SUCCESS'
